# products.py — GlowIQ Product Database
# buy_nykaa and buy_amazon use SEARCH URLs — always work, never 404

PRODUCT_DATABASE = {
    "cleansers": [
        {"name": "Cetaphil Gentle Skin Cleanser","brand": "Cetaphil","price": "₹299","tier": "Budget","category": "Cleanser","skin_types": ["Sensitive", "Dry", "Normal"],"concerns": ["Redness & Irritation", "Dryness & Flaking"],"time": ["am", "pm"],"key_ingredients": ["Glycerin", "Niacinamide"],"why": "Soap-free, fragrance-free formula that cleanses without stripping moisture. Ideal for sensitive and dry skin types.","buy_nykaa": "https://www.nykaa.com/search/result/?q=cetaphil+gentle+skin+cleanser","buy_amazon": "https://www.amazon.in/s?k=Cetaphil+Gentle+Skin+Cleanser"},
        {"name": "Minimalist 2% Salicylic Acid Face Wash","brand": "Minimalist","price": "₹299","tier": "Budget","category": "Cleanser","skin_types": ["Oily", "Combination", "Acne-prone"],"concerns": ["Acne & Breakouts", "Blackheads & Pores", "Oiliness"],"time": ["am", "pm"],"key_ingredients": ["Salicylic Acid 2%", "Zinc"],"why": "2% salicylic acid unclogs pores and reduces breakouts. Best for oily and acne-prone skin.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+salicylic+acid+face+wash","buy_amazon": "https://www.amazon.in/s?k=Minimalist+Salicylic+Acid+Face+Wash"},
        {"name": "Plum Green Tea Pore Cleansing Face Wash","brand": "Plum","price": "₹399","tier": "Budget","category": "Cleanser","skin_types": ["Oily", "Combination"],"concerns": ["Blackheads & Pores", "Oiliness", "Acne & Breakouts"],"time": ["am", "pm"],"key_ingredients": ["Green Tea Extract", "Glycolic Acid"],"why": "Green tea antioxidants control sebum while gently cleaning. 100% vegan, no SLS/SLES.","buy_nykaa": "https://www.nykaa.com/search/result/?q=plum+green+tea+face+wash","buy_amazon": "https://www.amazon.in/s?k=Plum+Green+Tea+Pore+Cleansing+Face+Wash"},
        {"name": "CeraVe Hydrating Facial Cleanser","brand": "CeraVe","price": "₹899","tier": "Mid-range","category": "Cleanser","skin_types": ["Dry", "Normal", "Sensitive"],"concerns": ["Dryness & Flaking", "Redness & Irritation"],"time": ["am", "pm"],"key_ingredients": ["Ceramides", "Hyaluronic Acid", "Niacinamide"],"why": "Contains ceramides and hyaluronic acid to cleanse while maintaining the skin barrier.","buy_nykaa": "https://www.nykaa.com/search/result/?q=cerave+hydrating+facial+cleanser","buy_amazon": "https://www.amazon.in/s?k=CeraVe+Hydrating+Facial+Cleanser"},
        {"name": "La Roche-Posay Effaclar Foaming Gel","brand": "La Roche-Posay","price": "₹1,199","tier": "Mid-range","category": "Cleanser","skin_types": ["Oily", "Combination"],"concerns": ["Acne & Breakouts", "Oiliness", "Blackheads & Pores"],"time": ["am", "pm"],"key_ingredients": ["Zinc Pidolate", "Zinc Gluconate"],"why": "Zinc pidolate controls shine while zinc gluconate purifies oily skin. Dermatologist-tested.","buy_nykaa": "https://www.nykaa.com/search/result/?q=la+roche+posay+effaclar+foaming+gel","buy_amazon": "https://www.amazon.in/s?k=La+Roche+Posay+Effaclar+Foaming+Gel"},
        {"name": "Tatcha The Rice Wash","brand": "Tatcha","price": "₹4,200","tier": "Premium","category": "Cleanser","skin_types": ["Dry", "Sensitive", "Normal"],"concerns": ["Dullness & Uneven Tone", "Dryness & Flaking"],"time": ["am", "pm"],"key_ingredients": ["Japanese Rice Bran", "Hyaluronic Acid"],"why": "Japanese rice bran cleanses and polishes with zero irritation. Leaves skin with an authentic mochi glow.","buy_nykaa": "https://www.nykaa.com/search/result/?q=tatcha+rice+wash","buy_amazon": "https://www.amazon.in/s?k=Tatcha+The+Rice+Wash"},
    ],
    "toners": [
        {"name": "Minimalist AHA 10% + PHA 3% Toner","brand": "Minimalist","price": "₹499","tier": "Budget","category": "Toner / Exfoliant","skin_types": ["Oily", "Normal", "Combination"],"concerns": ["Texture Issues", "Dullness & Uneven Tone", "Dark Spots & Pigmentation"],"time": ["pm"],"key_ingredients": ["AHA 10%", "PHA 3%"],"why": "AHA gently exfoliates dead skin cells, improving texture and tone. Use at night.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+aha+pha+toner","buy_amazon": "https://www.amazon.in/s?k=Minimalist+AHA+10+PHA+3+Toner"},
        {"name": "Pyunkang Yul Essence Toner","brand": "Pyunkang Yul","price": "₹799","tier": "Mid-range","category": "Toner","skin_types": ["Dry", "Sensitive", "Normal"],"concerns": ["Dryness & Flaking", "Redness & Irritation"],"time": ["am", "pm"],"key_ingredients": ["Astragalus Root Extract 96%"],"why": "96% Astragalus root extract deeply hydrates and soothes. Only 5 ingredients — ideal for reactive skin.","buy_nykaa": "https://www.nykaa.com/search/result/?q=pyunkang+yul+essence+toner","buy_amazon": "https://www.amazon.in/s?k=Pyunkang+Yul+Essence+Toner"},
        {"name": "Paula's Choice 2% BHA Liquid Exfoliant","brand": "Paula's Choice","price": "₹2,500","tier": "Premium","category": "Exfoliant","skin_types": ["Oily", "Combination", "Normal"],"concerns": ["Blackheads & Pores", "Acne & Breakouts", "Texture Issues"],"time": ["pm"],"key_ingredients": ["Salicylic Acid 2%", "Green Tea Extract"],"why": "Cult-favourite BHA exfoliant that visibly reduces pores and blackheads within weeks.","buy_nykaa": "https://www.nykaa.com/search/result/?q=paulas+choice+2+bha+liquid+exfoliant","buy_amazon": "https://www.amazon.in/s?k=Paula%27s+Choice+2%25+BHA+Liquid+Exfoliant"},
        {"name": "SK-II Facial Treatment Essence","brand": "SK-II","price": "₹12,000","tier": "Premium","category": "Essence","skin_types": ["All"],"concerns": ["Dullness & Uneven Tone", "Fine Lines & Wrinkles", "Loss of Firmness"],"time": ["am", "pm"],"key_ingredients": ["Pitera (Galactomyces Ferment Filtrate)"],"why": "Legendary Pitera essence used by top models. Transforms skin texture and radiance in 4 weeks.","buy_nykaa": "https://www.nykaa.com/search/result/?q=skii+facial+treatment+essence","buy_amazon": "https://www.amazon.in/s?k=SK-II+Facial+Treatment+Essence"},
    ],
    "serums": [
        {"name": "Minimalist 10% Niacinamide + Zinc Serum","brand": "Minimalist","price": "₹599","tier": "Budget","category": "Serum","skin_types": ["Oily", "Combination", "Normal"],"concerns": ["Acne & Breakouts", "Dark Spots & Pigmentation", "Oiliness", "Blackheads & Pores"],"time": ["am", "pm"],"key_ingredients": ["Niacinamide 10%", "Zinc 1%"],"why": "10% niacinamide reduces sebum, minimises pores, and fades dark spots. India's best-selling serum.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+niacinamide+10+zinc+serum","buy_amazon": "https://www.amazon.in/s?k=Minimalist+Niacinamide+10%25+Zinc+Serum"},
        {"name": "Minimalist 0.3% Retinol Serum","brand": "Minimalist","price": "₹699","tier": "Budget","category": "Serum","skin_types": ["Normal", "Combination", "Oily"],"concerns": ["Fine Lines & Wrinkles", "Acne & Breakouts", "Texture Issues", "Dark Spots & Pigmentation"],"time": ["pm"],"key_ingredients": ["Retinol 0.3%", "Squalane"],"why": "Retinol accelerates cell turnover, smoothing wrinkles and fading scars. Start 2x/week and build tolerance.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+retinol+0.3+serum","buy_amazon": "https://www.amazon.in/s?k=Minimalist+0.3%25+Retinol+Serum"},
        {"name": "The Ordinary Hyaluronic Acid 2% + B5","brand": "The Ordinary","price": "₹590","tier": "Budget","category": "Serum","skin_types": ["All"],"concerns": ["Dryness & Flaking", "Fine Lines & Wrinkles"],"time": ["am", "pm"],"key_ingredients": ["Hyaluronic Acid 2%", "Vitamin B5"],"why": "Multi-weight hyaluronic acid hydrates at every skin layer. Apply on damp skin for maximum plumping.","buy_nykaa": "https://www.nykaa.com/search/result/?q=the+ordinary+hyaluronic+acid+2+b5","buy_amazon": "https://www.amazon.in/s?k=The+Ordinary+Hyaluronic+Acid+2%25+B5"},
        {"name": "Plum 15% Vitamin C Serum","brand": "Plum","price": "₹699","tier": "Budget","category": "Serum","skin_types": ["Normal", "Dry", "Combination"],"concerns": ["Dullness & Uneven Tone", "Dark Spots & Pigmentation", "Sun Damage"],"time": ["am"],"key_ingredients": ["Vitamin C 15%", "Vitamin E"],"why": "Stable Vitamin C derivative brightens and protects from free radical damage. Use every morning before SPF.","buy_nykaa": "https://www.nykaa.com/search/result/?q=plum+15+vitamin+c+serum","buy_amazon": "https://www.amazon.in/s?k=Plum+15%25+Vitamin+C+Serum"},
        {"name": "Dot & Key Barrier Repair Ceramide Serum","brand": "Dot & Key","price": "₹799","tier": "Budget","category": "Serum","skin_types": ["Dry", "Sensitive"],"concerns": ["Dryness & Flaking", "Redness & Irritation", "Texture Issues"],"time": ["am", "pm"],"key_ingredients": ["Ceramide-3", "Peptides", "Niacinamide"],"why": "Ceramide-3 + peptide blend repairs a damaged skin barrier. Skin feels plump and calm after first use.","buy_nykaa": "https://www.nykaa.com/search/result/?q=dot+key+barrier+repair+ceramide+serum","buy_amazon": "https://www.amazon.in/s?k=Dot+Key+Barrier+Repair+Ceramide+Serum"},
        {"name": "Olay Regenerist Micro-Sculpting Serum","brand": "Olay","price": "₹1,299","tier": "Mid-range","category": "Serum","skin_types": ["Normal", "Dry", "Combination"],"concerns": ["Fine Lines & Wrinkles", "Loss of Firmness", "Dullness & Uneven Tone"],"time": ["am", "pm"],"key_ingredients": ["Amino-Peptide Complex", "Niacinamide", "Hyaluronic Acid"],"why": "Amino-peptide complex + niacinamide visibly firms and plumps skin. Lightweight, absorbs fast.","buy_nykaa": "https://www.nykaa.com/search/result/?q=olay+regenerist+micro+sculpting+serum","buy_amazon": "https://www.amazon.in/s?k=Olay+Regenerist+Micro+Sculpting+Serum"},
        {"name": "Kiehl's Midnight Recovery Concentrate","brand": "Kiehl's","price": "₹3,500","tier": "Premium","category": "Face Oil / Serum","skin_types": ["Dry", "Normal", "Sensitive"],"concerns": ["Dryness & Flaking", "Fine Lines & Wrinkles", "Dullness & Uneven Tone"],"time": ["pm"],"key_ingredients": ["Lavender Oil", "Evening Primrose Oil", "Squalane"],"why": "Lavender + primrose oils work overnight to restore and regenerate. Wake up to visibly improved skin.","buy_nykaa": "https://www.nykaa.com/search/result/?q=kiehls+midnight+recovery+concentrate","buy_amazon": "https://www.amazon.in/s?k=Kiehl%27s+Midnight+Recovery+Concentrate"},
        {"name": "SkinCeuticals C E Ferulic","brand": "SkinCeuticals","price": "₹14,500","tier": "Premium","category": "Serum","skin_types": ["All"],"concerns": ["Sun Damage", "Fine Lines & Wrinkles", "Dullness & Uneven Tone", "Dark Spots & Pigmentation"],"time": ["am"],"key_ingredients": ["L-Ascorbic Acid 15%", "Vitamin E 1%", "Ferulic Acid 0.5%"],"why": "The gold standard Vitamin C serum. Triple antioxidant formula for maximum UV and pollution protection.","buy_nykaa": "https://www.nykaa.com/search/result/?q=skinceuticals+ce+ferulic","buy_amazon": "https://www.amazon.in/s?k=SkinCeuticals+CE+Ferulic+Serum"},
        {"name": "Estee Lauder Advanced Night Repair","brand": "Estee Lauder","price": "₹8,500","tier": "Premium","category": "Serum","skin_types": ["All"],"concerns": ["Fine Lines & Wrinkles", "Dullness & Uneven Tone", "Loss of Firmness"],"time": ["pm"],"key_ingredients": ["Hyaluronic Acid", "Bifida Ferment Lysate", "Caffeine"],"why": "Chronolux technology syncs with skin's natural night repair cycle. Reduces fine lines in 4 weeks.","buy_nykaa": "https://www.nykaa.com/search/result/?q=estee+lauder+advanced+night+repair","buy_amazon": "https://www.amazon.in/s?k=Estee+Lauder+Advanced+Night+Repair+Serum"},
    ],
    "moisturisers": [
        {"name": "Cetaphil Moisturising Cream","brand": "Cetaphil","price": "₹399","tier": "Budget","category": "Moisturiser","skin_types": ["Dry", "Sensitive", "Normal"],"concerns": ["Dryness & Flaking", "Redness & Irritation"],"time": ["am", "pm"],"key_ingredients": ["Glycerin", "Petrolatum", "Dimethicone"],"why": "Non-comedogenic, fragrance-free cream that deeply hydrates without clogging pores. Dermatologist staple.","buy_nykaa": "https://www.nykaa.com/search/result/?q=cetaphil+moisturising+cream","buy_amazon": "https://www.amazon.in/s?k=Cetaphil+Moisturising+Cream"},
        {"name": "Plum Hello Aloe Deep Moisturiser","brand": "Plum","price": "₹399","tier": "Budget","category": "Moisturiser","skin_types": ["Oily", "Combination"],"concerns": ["Oiliness", "Acne & Breakouts"],"time": ["am", "pm"],"key_ingredients": ["Aloe Vera", "Hyaluronic Acid"],"why": "Aloe vera-based, oil-free gel moisturiser that hydrates without greasiness. Vegan and non-comedogenic.","buy_nykaa": "https://www.nykaa.com/search/result/?q=plum+hello+aloe+moisturiser","buy_amazon": "https://www.amazon.in/s?k=Plum+Hello+Aloe+Deep+Moisturiser"},
        {"name": "Neutrogena Hydro Boost Water Gel","brand": "Neutrogena","price": "₹849","tier": "Mid-range","category": "Moisturiser","skin_types": ["Oily", "Combination", "Normal"],"concerns": ["Oiliness", "Dryness & Flaking"],"time": ["am", "pm"],"key_ingredients": ["Hyaluronic Acid", "Dimethicone"],"why": "Hyaluronic acid gel locks in moisture. Lightweight texture perfect for India's humid climate.","buy_nykaa": "https://www.nykaa.com/search/result/?q=neutrogena+hydro+boost+water+gel","buy_amazon": "https://www.amazon.in/s?k=Neutrogena+Hydro+Boost+Water+Gel"},
        {"name": "CeraVe Moisturising Cream","brand": "CeraVe","price": "₹1,199","tier": "Mid-range","category": "Moisturiser","skin_types": ["Dry", "Sensitive", "Normal"],"concerns": ["Dryness & Flaking", "Redness & Irritation", "Texture Issues"],"time": ["am", "pm"],"key_ingredients": ["Ceramide NP", "Ceramide AP", "Hyaluronic Acid"],"why": "3 essential ceramides + hyaluronic acid restore and maintain the skin barrier.","buy_nykaa": "https://www.nykaa.com/search/result/?q=cerave+moisturising+cream","buy_amazon": "https://www.amazon.in/s?k=CeraVe+Moisturising+Cream"},
        {"name": "La Mer Creme de la Mer","brand": "La Mer","price": "₹18,000","tier": "Premium","category": "Moisturiser","skin_types": ["Dry", "Sensitive"],"concerns": ["Dryness & Flaking", "Fine Lines & Wrinkles", "Loss of Firmness"],"time": ["am", "pm"],"key_ingredients": ["Miracle Broth (Sea Kelp)", "Lime Tea Extract"],"why": "The iconic miracle broth cream. Kelp-based biotechnology restores and regenerates dry, damaged skin.","buy_nykaa": "https://www.nykaa.com/search/result/?q=la+mer+creme+de+la+mer","buy_amazon": "https://www.amazon.in/s?k=La+Mer+Creme+de+la+Mer"},
    ],
    "eye_creams": [
        {"name": "Minimalist Caffeine 5% + EGCG Eye Serum","brand": "Minimalist","price": "₹499","tier": "Budget","category": "Eye Serum","skin_types": ["All"],"concerns": ["Dark Circles", "Fine Lines & Wrinkles"],"time": ["am"],"key_ingredients": ["Caffeine 5%", "EGCG", "Hyaluronic Acid"],"why": "Caffeine constricts blood vessels to reduce puffiness; EGCG tackles dark circles. Apply with ring finger.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+caffeine+eye+serum","buy_amazon": "https://www.amazon.in/s?k=Minimalist+Caffeine+5%25+EGCG+Eye+Serum"},
        {"name": "Kiehl's Creamy Eye Treatment Avocado","brand": "Kiehl's","price": "₹3,200","tier": "Premium","category": "Eye Cream","skin_types": ["Dry", "Normal"],"concerns": ["Dark Circles", "Fine Lines & Wrinkles", "Dryness & Flaking"],"time": ["pm"],"key_ingredients": ["Avocado Oil", "Shea Butter", "Beta-Carotene"],"why": "Rich avocado oil cream nourishes the delicate eye area overnight. Reduces fine lines and dryness.","buy_nykaa": "https://www.nykaa.com/search/result/?q=kiehls+creamy+eye+treatment+avocado","buy_amazon": "https://www.amazon.in/s?k=Kiehl%27s+Creamy+Eye+Treatment+Avocado"},
    ],
    "sunscreens": [
        {"name": "Minimalist SPF 50 PA++++ Sunscreen","brand": "Minimalist","price": "₹399","tier": "Budget","category": "Sunscreen","skin_types": ["All"],"concerns": ["Sun Damage", "Dark Spots & Pigmentation", "Fine Lines & Wrinkles"],"time": ["am"],"key_ingredients": ["Zinc Oxide", "Octinoxate", "Niacinamide"],"why": "Lightweight, no white cast, SPF 50 PA++++. Non-greasy finish. India's best-value SPF.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+spf+50+sunscreen","buy_amazon": "https://www.amazon.in/s?k=Minimalist+SPF+50+Sunscreen"},
        {"name": "Dot & Key Waterlight Gel Sunscreen SPF 50","brand": "Dot & Key","price": "₹599","tier": "Budget","category": "Sunscreen","skin_types": ["Oily", "Combination", "Sensitive"],"concerns": ["Oiliness", "Redness & Irritation", "Sun Damage"],"time": ["am"],"key_ingredients": ["Niacinamide", "Hyaluronic Acid", "Zinc Oxide"],"why": "Water-light gel formula absorbs instantly with no grease. Niacinamide adds a brightening bonus.","buy_nykaa": "https://www.nykaa.com/search/result/?q=dot+key+waterlight+gel+sunscreen","buy_amazon": "https://www.amazon.in/s?k=Dot+Key+Waterlight+Gel+Sunscreen+SPF+50"},
        {"name": "La Roche-Posay Anthelios SPF 50+","brand": "La Roche-Posay","price": "₹1,999","tier": "Mid-range","category": "Sunscreen","skin_types": ["All"],"concerns": ["Sun Damage", "Redness & Irritation", "Dark Spots & Pigmentation"],"time": ["am"],"key_ingredients": ["Mexoryl XL", "Tinosorb S", "Thermal Spring Water"],"why": "Broad-spectrum SPF 50+ with Mexoryl XL. Ultra-fluid finish loved by dermatologists globally.","buy_nykaa": "https://www.nykaa.com/search/result/?q=la+roche+posay+anthelios+spf+50","buy_amazon": "https://www.amazon.in/s?k=La+Roche+Posay+Anthelios+SPF+50"},
    ],
    "spot_treatments": [
        {"name": "Minimalist 10% Benzoyl Peroxide Gel","brand": "Minimalist","price": "₹399","tier": "Budget","category": "Spot Treatment","skin_types": ["Oily", "Combination"],"concerns": ["Acne & Breakouts"],"time": ["pm"],"key_ingredients": ["Benzoyl Peroxide 10%"],"why": "Benzoyl peroxide kills acne bacteria directly in pores. Apply only on active breakouts.","buy_nykaa": "https://www.nykaa.com/search/result/?q=minimalist+benzoyl+peroxide+gel","buy_amazon": "https://www.amazon.in/s?k=Minimalist+Benzoyl+Peroxide+Gel"},
        {"name": "Mario Badescu Drying Lotion","brand": "Mario Badescu","price": "₹1,200","tier": "Mid-range","category": "Spot Treatment","skin_types": ["Oily", "Combination"],"concerns": ["Acne & Breakouts"],"time": ["pm"],"key_ingredients": ["Salicylic Acid", "Sulfur", "Calamine"],"why": "Cult overnight spot treatment. Dip a cotton swab into the pink layer and dab on blemishes.","buy_nykaa": "https://www.nykaa.com/search/result/?q=mario+badescu+drying+lotion","buy_amazon": "https://www.amazon.in/s?k=Mario+Badescu+Drying+Lotion"},
    ],
    "masks": [
        {"name": "Mamaearth Charcoal Face Mask","brand": "Mamaearth","price": "₹349","tier": "Budget","category": "Face Mask","skin_types": ["Oily", "Combination"],"concerns": ["Blackheads & Pores", "Oiliness", "Acne & Breakouts"],"time": ["pm"],"key_ingredients": ["Activated Charcoal", "Kaolin Clay"],"why": "Activated charcoal draws out impurities from pores. Use weekly for a deep-clean ritual.","buy_nykaa": "https://www.nykaa.com/search/result/?q=mamaearth+charcoal+face+mask","buy_amazon": "https://www.amazon.in/s?k=Mamaearth+Charcoal+Face+Mask"},
        {"name": "Innisfree Super Volcanic Pore Clay Mask","brand": "Innisfree","price": "₹1,200","tier": "Mid-range","category": "Face Mask","skin_types": ["Oily", "Combination", "Normal"],"concerns": ["Blackheads & Pores", "Oiliness", "Texture Issues"],"time": ["pm"],"key_ingredients": ["Jeju Volcanic Clusters", "Kaolin", "Bentonite"],"why": "Jeju volcanic clusters absorb excess sebum and extract blackheads. The gold standard clay mask.","buy_nykaa": "https://www.nykaa.com/search/result/?q=innisfree+super+volcanic+pore+clay+mask","buy_amazon": "https://www.amazon.in/s?k=Innisfree+Super+Volcanic+Pore+Clay+Mask"},
        {"name": "Fresh Rose Face Mask","brand": "Fresh","price": "₹4,200","tier": "Premium","category": "Face Mask","skin_types": ["Dry", "Sensitive", "Normal"],"concerns": ["Dryness & Flaking", "Redness & Irritation", "Dullness & Uneven Tone"],"time": ["pm"],"key_ingredients": ["Real Rose Petals", "Hyaluronic Acid", "Rosewater"],"why": "Real rose petals in a hyaluronic acid gel formula. Intensely soothes and hydrates in 10 minutes.","buy_nykaa": "https://www.nykaa.com/search/result/?q=fresh+rose+face+mask","buy_amazon": "https://www.amazon.in/s?k=Fresh+Rose+Face+Mask"},
    ],
}
